export const dataServices = [
  {
    id: 1,
    icon: `icon-1889287`,
    title: `Gas Heater Installation`,
    text: `Our specialists provide professional installation of all types of gas heating systems, ensuring safe and efficient operation for your home or business.`,
    list: [
      "Ducted Gas Heating Systems",
      "Gas Wall Furnaces",
      "Gas Space Heaters",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__residential",
  },
  {
    id: 2,
    icon: `icon-2424820`,
    title: `Gas Heater Servicing`,
    text: `Regular servicing keeps your gas heater running efficiently and safely. Our team offers thorough maintenance and inspections for all major brands.`,
    list: [
      "Annual Maintenance & Tune-Ups",
      "Carbon Monoxide Testing",
      "System Performance Checks",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__commercial",
  },
  {
    id: 3,
    icon: `icon-1677058`,
    title: `Gas Heater Repairs`,
    text: `We provide fast and reliable repair services for faulty or underperforming gas heaters, restoring warmth and safety to your property.`,
    list: [
      "No Heat or Insufficient Heating",
      "Unusual Noises or Smells",
      "Ignition or Thermostat Issues",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__emergency",
  },
  {
    id: 4,
    icon: `icon-3731419`,
    title: `Emergency Gas Heater Repairs`,
    text: `Our experts are available 24/7 for urgent gas heater repairs, ensuring your comfort and safety in any situation.`,
    list: ["Gas Leaks or Odours", "Sudden Heater Failure", "Safety Concerns"],
    btn__text: "Know more",
    btn__src: "/services/services__residential",
  },
  {
    id: 5,
    icon: `icon-2321403`,
    title: `Gas Heater Upgrades & Replacements`,
    text: `Upgrade to a more energy-efficient gas heater or replace outdated systems with our expert advice and installation services.`,
    list: [
      "High-Efficiency Heating Options",
      "System Upgrades & Modernization",
      "Reliable Replacement Solutions",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__commercial",
  },
];
