export const dataServices = [
  {
    id: 1,
    icon: `icon-1889287`,
    title: `Ducted Heating Installation`,
    text: `Our specialists provide professional installation of all types of ducted heating systems, ensuring energy-efficient and comfortable operation for your home or business.`,
    list: [
      "Central Ducted Heating Systems",
      "Zone Control Installation",
      "Thermostat & Controls Setup",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__residential",
  },
  {
    id: 2,
    icon: `icon-2424820`,
    title: `Ducted Heating Servicing`,
    text: `Regular servicing keeps your ducted heating system running efficiently and reliably. Our team offers thorough maintenance and inspections for all major brands.`,
    list: [
      "Annual Maintenance & Tune-Ups",
      "Filter Replacement & Cleaning",
      "System Performance Optimization",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__commercial",
  },
  {
    id: 3,
    icon: `icon-1677058`,
    title: `Ducted Heating Repairs`,
    text: `We provide fast and reliable repair services for faulty or underperforming ducted heating systems, restoring warmth and comfort to your property.`,
    list: [
      "No Heat or Insufficient Heating",
      "Duct Leaks & Airflow Issues",
      "Thermostat & Control Problems",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__emergency",
  },
  {
    id: 4,
    icon: `icon-3731419`,
    title: `Emergency Ducted Heating Repairs`,
    text: `Our experts are available 24/7 for urgent ducted heating repairs, ensuring your comfort and safety in any heating emergency situation.`,
    list: [
      "System Complete Failure",
      "Duct Damage or Blockages",
      "Heating Emergencies",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__residential",
  },
  {
    id: 5,
    icon: `icon-2321403`,
    title: `Ducted Heating Upgrades & Replacements`,
    text: `Upgrade to a more energy-efficient ducted heating system or replace outdated systems with our expert advice and installation services.`,
    list: [
      "High-Efficiency Heating Options",
      "System Upgrades & Modernization",
      "Smart Control Integration",
    ],
    btn__text: "Know more",
    btn__src: "/services/services__commercial",
  },
];
