export const MainSliderData = [
	{
		id: 1,
		layout:'type1',
		youtubeVideoCode: "wHPqgzlRasA",
		bgimg_lg_jpg: '/images/main-slider/slide01__bg_lg.jpg',
		bgimg_lg_webp: '/images/main-slider/slide01__bg_lg.webp',
		bgimg_md_jpg: '/images/main-slider/slide01__bg_md.jpg',
		bgimg_md_webp: '/images/main-slider/slide01__bg_md.webp',
		bgimg_sm_jpg: '/images/main-slider/slide01__bg_sm.jpg',
		bgimg_sm_webp: '/images/main-slider/slide01__bg_sm.webp',
		srcimg_lg_png: '/images/main-slider/slide01__lg.png',
		srcimg_lg_webp: '/images/main-slider/slide01__lg.webp',
		srcimg_md_png: '/images/main-slider/slide01__md.png',
		srcimg_md_webp: '/images/main-slider/slide01__md.webp',
		title: `Need Help with a Plumbing Emergency?`,
		text: `Whether you need new plumbing equipment installed or existing plumbing repaired, we're here to help.`,
	},
	{
		id: 2,
		layout:'type2',
		bgimg_lg_jpg: '/images/main-slider/slide02__bg_lg.jpg',
		bgimg_lg_webp: '/images/main-slider/slide02__bg_lg.webp',
		bgimg_md_jpg: '/images/main-slider/slide02__bg_md.jpg',
		bgimg_md_webp: '/images/main-slider/slide02__bg_md.webp',
		bgimg_sm_jpg: '/images/main-slider/slide02__bg_sm.jpg',
		bgimg_sm_webp: '/images/main-slider/slide02__bg_sm.webp',
		srcimg_lg_png: '/images/main-slider/slide02__lg.png',
		srcimg_lg_webp: '/images/main-slider/slide02__lg.webp',
		srcimg_md_png: '/images/main-slider/slide02__md.png',
		srcimg_md_webp: '/images/main-slider/slide02__md.webp',
		title: `Exceptional, Punctual &  Professional`,
		text: `You deserve to have a handy team of plumbers who can install or repair any plumbing system you need.`,
	},
];
