export const dataPlans = [
	{
		id: 1,
		icon: 'icon-701142',
		title: 'Residential \n Plumbing Plan',
		list: [
			'Get 10% OFF all parts and repairs',
			'Test Water Pressure',
			'Identify Shut-Off Valves',
			'Priority service',
		],
		price: '$134.99',
		period: 'month',
		btn__text: 'Get this Plan',
		btn__src: '/services/services__residential',
	},
	{
		id: 2,
		icon: 'icon-857333',
		title: 'Water Heater \n Maintenance Plan',
		list: [
			'Exclusive Customer Benefits',
			'Boiler + Controls',
			'Annual Boiler Service',
			'Unlimited Call Outs',
		],
		price: '$14.99',
		period: 'month',
		btn__text: 'Get this Plan',
		btn__src: '/services/services__commercial',
	},
	{
		id: 3,
		icon: 'icon-2321403',
		title: 'Commercial \n Plumbing Plan',
		list: [
			'15% Discount on Repairs',
			'Priority Scheduling',
			'Maintained Equipment Efficiency',
			'Extended Equipment Life',
		],
		price: '$1029.99',
		period: 'month',
		btn__text: 'Get this Plan',
		btn__src: '/services/services__emergency',
	},
	{
		id: 4,
		icon: 'icon-701142',
		title: 'Plumbing \n Plan',
		list: [
			'Get 10% OFF all parts and repairs',
			'Test Water Pressure',
			'Identify Shut-Off Valves',
			'Priority service',
		],
		price: '$134.99',
		period: 'month',
		btn__text: 'Get this Plan',
		btn__src: '/services/services__residential',
	},
	{
		id: 5,
		icon: 'icon-857333',
		title: 'Boiler \n Service Plan',
		list: [
			'Exclusive Customer Benefits',
			'Boiler + Controls',
			'Annual Boiler Service',
			'Unlimited Call Outs',
		],
		price: '$14.99',
		period: 'month',
		btn__text: 'Get this Plan',
		btn__src: '/services/services__emergency',
	},
	{
		id: 6,
		icon: 'icon-2321403',
		title: 'Commercial \n Plumbing Plan',
		list: [
			'15% Discount on Repairs',
			'Priority Scheduling',
			'Maintained Equipment Efficiency',
			'Extended Equipment Life',
		],
		price: '$1029.99',
		period: 'month',
		btn__text: 'Get this Plan',
		btn__src: '/services/services__commercial',
	},
];
