export const dataServices = [
  {
    id: 1,
    title: "Residential Ducted Heating",
    subtitle: "Services",
    icon: "icon-3731419",
    srcLink: "/services/services__residential",
    srcimg: "/images/imgbox-inner__img01.jpg",
    text: "Keep your home comfortable and energy-efficient with professional ducted heating solutions. Ensure your ducted heating system is operating efficiently and reliably all year round. Here's a sample of the expert services we offer for Melbourne households.",
    list: [
      "Ducted Heating Repairs & Installation",
      "Regular System Servicing & Maintenance",
      "Duct Cleaning & Sanitisation",
      "Zone Control System Installation",
      "Thermostat Upgrades & Repairs",
    ],
  },
  {
    id: 2,
    title: "Commercial Ducted Heating",
    subtitle: "Services",
    icon: "icon-16770581",
    srcLink: "/services/services__commercial",
    srcimg: "/images/imgbox-inner__img02.jpg",
    text: "Providing reliable and efficient ducted heating is our top priority for Melbourne businesses. Our experienced technicians are equipped with the latest training and technology to ensure your premises stay warm and comfortable.",
    list: [
      "Commercial Ducted Heating Repairs & Installation",
      "Routine System Servicing & Maintenance",
      "Comprehensive Duct Cleaning & Sanitisation",
      "Multi-Zone Ducted Heating System Installation & Upgrades",
      "Energy Efficiency Audits & System Optimisation",
    ],
  },
  {
    id: 3,
    title: "Emergency Ducted Heating",
    subtitle: "Services",
    icon: "icon-1889287",
    srcLink: "/services/services__emergency",
    srcimg: "/images/imgbox-inner__img03.jpg",
    text: "No matter when you need help, our team is available 24/7 for urgent ducted heating issues. Our experienced technicians respond quickly to emergency calls, including after-hours and holidays, to keep your home or business warm and comfortable.",
    list: [
      "Emergency Ducted Heating Repairs & Installation",
      "Urgent System Servicing & Maintenance",
      "24/7 Duct Cleaning & Emergency Repairs",
      "Rapid Zone Control System Installation",
      "Immediate Thermostat & Control Repairs",
    ],
  },
];
