export const dataAreasCover = [
  { id: 1, county: "Armadale", state: "Melbourne", link: "/" },
  { id: 2, county: "Ashwood", state: "Melbourne", link: "/" },
  { id: 3, county: "Attwood", state: "Melbourne", link: "/" },
  { id: 4, county: "Avonsleigh", state: "Melbourne", link: "/" },
  { id: 5, county: "Badger Creek", state: "Melbourne", link: "/" },
  { id: 6, county: "Bayswater", state: "Melbourne", link: "/" },
  { id: 7, county: "Baxter", state: "Melbourne", link: "/" },
  { id: 8, county: "Beaconsfield", state: "Melbourne", link: "/" },
  { id: 9, county: "Belgrave", state: "Melbourne", link: "/" },
  { id: 10, county: "Bentleigh", state: "Melbourne", link: "/" },
  { id: 11, county: "Bentleigh East", state: "Melbourne", link: "/" },
  { id: 12, county: "Berwick", state: "Melbourne", link: "/" },
  { id: 13, county: "Beaumaris", state: "Melbourne", link: "/" },
  { id: 14, county: "Bittern", state: "Melbourne", link: "/" },
];
