export const dataAreasCover = [
  { id: 1, county: "Armadale", state: "Melbourne", link: "/coverage/armadale" },
  { id: 2, county: "Ashwood", state: "Melbourne", link: "/coverage/ashwood" },
  { id: 3, county: "Attwood", state: "Melbourne", link: "/coverage/attwood" },
  {
    id: 4,
    county: "Avonsleigh",
    state: "Melbourne",
    link: "/coverage/avonsleigh",
  },
  {
    id: 5,
    county: "Badger Creek",
    state: "Melbourne",
    link: "/coverage/badger-creek",
  },
  {
    id: 6,
    county: "Bayswater",
    state: "Melbourne",
    link: "/coverage/bayswater",
  },
  { id: 7, county: "Baxter", state: "Melbourne", link: "/coverage/baxter" },
  {
    id: 8,
    county: "Beaconsfield",
    state: "Melbourne",
    link: "/coverage/beaconsfield",
  },
  { id: 9, county: "Belgrave", state: "Melbourne", link: "/coverage/belgrave" },
  {
    id: 10,
    county: "Bentleigh",
    state: "Melbourne",
    link: "/coverage/bentleigh",
  },
  {
    id: 11,
    county: "Bentleigh East",
    state: "Melbourne",
    link: "/coverage/bentleigh-east",
  },
  { id: 12, county: "Berwick", state: "Melbourne", link: "/coverage/berwick" },
  {
    id: 13,
    county: "Beaumaris",
    state: "Melbourne",
    link: "/coverage/beaumaris",
  },
  { id: 14, county: "Bittern", state: "Melbourne", link: "/coverage/bittern" },
];
